### ISSUE TITLE
Migration from the Azure SDK to the Azure Storage SDK

### ISSUE THREAD

**Issue by olsgreen** [thephpleague/flysystem-azure#14]
I've been hitting a few problems using the adapter, namely HTTP headers being set incorrectly.

Turns out that the Azure SDK doesn't receive proper updates for it's storage APIs, Microsoft has recommended migrating over to the dedicated storage api which does:

https://github.com/Azure/azure-storage-php#migrate-from-azure-sdk-for-php

Is this in the plans? I don't mind doing it...

**Comment by frankdejonge** [comment]
The PR that fixed this is merged, will be tagged as 1.0.4.
