### ISSUE TITLE
Unable to use Azure Storage Emulator

### ISSUE THREAD

**Issue by kyleweishaupt** [thephpleague/flysystem-azure#21]
Hi. I'm trying to use the Azure Storage Emulator when developing offline, but the older releases of the Azure SDK do not support the emulator.

I created an issue with the Azure SDK (https://github.com/Azure/azure-storage-php/issues/58) and they released 0.13.0 with support for using 'UseDevelopmentStorage=true;' as the connection string. I'm just wondering if the adapter could be updated to the latest SDK version.

Thanks!

**Comment by cberio** [comment]
👍
