### ISSUE TITLE
why no ServiceProvider, so we can use config/filesystems.php

### ISSUE THREAD

**Issue by sinkcup** [thephpleague/flysystem-azure#25]
other driver has ServiceProvider, 
like: https://github.com/Superbalist/laravel-google-cloud-storage

so we can use `config/filesystems.php`
```
'gcs' => [
    'driver' => 'gcs',
    'project_id' => env('GOOGLE_CLOUD_PROJECT_ID', 'your-project-id'),
    'key_file' => env('GOOGLE_CLOUD_KEY_FILE', null),
]
```

then we can use code like https://laravel.com/docs/5.4/filesystem

```
Storage::disk('gcs')->put('file.txt', 'Contents');
```

why this project not have ServiceProvider? so we can use like:

```
        'azure' => [
            'driver'    => 'azure',
            'name'      => env('STORAGE_NAME'),
            'key'       => env('STORAGE_KEY'),
            'container' => env('STORAGE_CONTAINER'),
        ],

Storage::disk('azure')->put('file.txt', 'Contents');
```

see http://matthewdaly.co.uk/blog/2016/10/24/creating-an-azure-storage-adapter-for-laravel/

**Comment by twistor** [comment]
Creating framework specific glue code is outside the scope of Flysystem. This would get out of hand in a hurry as every framework needs something.

If you notice, the project https://github.com/Superbalist/laravel-google-cloud-storage is separate from the actual adapter.
