### ISSUE TITLE
flysystem-azure need pear-pear.php.net/mail_mime

### ISSUE THREAD

**Issue by adamkrupa** [thephpleague/flysystem-azure#3]
Hi, I would like to install this package but I get error from composer:
```
The requested package pear-pear.php.net/mail_mime could not be found in any version, there may be a typo in the package name.
```
I think that name "pear-pear.php.net" is not correct.

**Comment by gregrobson** [comment]
I managed to get it working for me.

Add the following to your root `composer.json` file (taken from https://github.com/thephpleague/flysystem-azure/blob/master/composer.json)

```javascript
    "repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net"
        }
    ],
```

This will alias the pear requests so it finds them in the right place. My guess is that the **repositories** property only works on the root `composer.json` and it's ignored in vendor packages (as it could easily cause conflicts).

This worked for my Laravel 5 installation.

**Comment by frankdejonge** [comment]
@adamkrupa Sorry for the late reply but the comment @gregrobson posted is correct. I'll add this to the readme too.
