### ISSUE TITLE
one adapter for multiple containers. is it possible? 

### ISSUE THREAD

**Issue by kopaygorodsky** [thephpleague/flysystem-azure#31]

**Comment by frankdejonge** [comment]
Hi @kopaygorodsky Flysystem's design is 1 to 1. One container per adapter, the rest of flysystem also only supports one to one. You can use the MountManager to perform multi filesystem operations tho.

**Comment by kopaygorodsky** [comment]
@frankdejonge thank you for a reply!

**Comment by frankdejonge** [comment]
You're welcome, @kopaygorodsky 👍
