### ISSUE TITLE
Pear packages re-located

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/flysystem-azure#6]
I believe these packages to be relocated under pear namespace, for example:

https://packagist.org/packages/pear/mail_mime

**Comment by frankdejonge** [comment]
@yellow1912 as far as I know, this adapter can only move them if the Azure SDK does this, in which case I can just drop those dependencies all-together. Though the SDK hasn't dropped then, so I can't.

**Comment by yellow1912** [comment]
@frankdejonge if we do not have direct dependencies on those packages (since we require azure and then azure require pear packages) perhaps we can drop those in this package and leave that to azure. Also, I submitted the same ticket to Azure, lets see if they will update soon. As of now composer update will fail without manually override this and azure package at the same time
